### ISSUE TITLE
Affichage du simulateur avec la dernière version de master

### ISSUE THREAD

**Issue by plorgue** [plorgue/simple-playgrounds-epuck#3]
Bonjour à tous,
J'espère que les fêtes se passe bien pour vous.

Comme on se l'était dit lors de notre dernière réunion au lieu d'utiliser la version de simple-playgrounds sur pip j'ai installé la dernière version de la branche master. 
Il me semble qu'il n'est plus possible d'afficher le simulateur avec cette version. Il n'y a plus le paramètre `screen` dans le constructeur d'`Engine`. Il est possible d'avoir un affichage en ajoutant un agent avec un controller `Keyboard` mais la fenêtre ne fait pas la taille du playground et est toute petite et on n'utilise pas de controller `Keyboard` dans tous les cas.

@gaorkl  Est ce que j'ai loupé quelque chose dans le code ? est ce qu'il faut qu'on utilise une autre version de spg ?

Merci d'avance pour votre aide

**Comment by gaorkl** [comment]
En effet il n'y a plus de screen. A la place vous pouvez toujours récupérer l'image de l'environnement grâce aux methodes dans engine.

Il y a des examples dans le dossier scripts, dites moi si ça n'est pas clair.

**Comment by plorgue** [comment]
D'accord je vois. Dans un premier temps récupérer des images suffit mais il sera je pense nécessaire d'avoir un screen sur lequel voir les agents évoluer en continue. Quelle solution pourront nous utiliser alors ?

**Comment by plorgue** [comment]
Bonjour @gaorkl, quelle solution avons nous pour pouvoir afficher en temps réel l'évolution de l'environnement en utilisant une des dernière version de spg ?

**Comment by gaorkl** [comment]
Vous pouvez utiliser une librairie qui permet d'afficher les images. Opencv, skimage, ou matplotlib. Il y aura peut être une conversion à faire de l'image selon la librairie que vous utilisez.
